org: fatimapv  # Actualiza con tu organización
service: api-web-scraping-sismos

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  memorySize: 2048
  timeout: 25   # Máximo permitido por API Gateway (29s)
  iam:
    role: arn:aws:iam::076456812464:role/LabRole

  ecr:
    images:
      scraping-sismos:
        path: ./  # usa tu Dockerfile en este mismo folder

functions:
  scrape_sismos:
    image:
      name: scraping-sismos
    events:
      - httpApi:
          path: /scrape/sismos
          method: GET
          cors: true

resources:
  Resources:
    TablaSismosIGP:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaSismosIGP
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
