org: fatimapv  # Tu organización en Serverless
service: api-web-scraping-sismos

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  memorySize: 2048        # Playwright necesita más memoria
  timeout: 25             # < 29s de límite de API Gateway
  iam:
    role: arn:aws:iam::076456812464:role/LabRole
  ecr:
    images:
      scraping-sismos:
        path: ./          # Usa tu Dockerfile del proyecto actual

functions:
  scrape_sismos:
    image:
      name: scraping-sismos
    events:
      - http:
          path: /scrape/sismos
          method: get
          cors: true       # Igual que en la tarea de bomberos
          integration: lambda

resources:
  Resources:
    TablaSismosIGP:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaSismosIGP
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
